import { ExecutionContext, createParamDecorator } from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';
import { FieldNode } from 'graphql';

/**
 * Extracts the requested fields at the GraphQL query and return it as a arrary of strings
 */
export const GraphQLQueryFields = createParamDecorator(
  (data: unknown, ctx: ExecutionContext) => {
    const gqlContext = GqlExecutionContext.create(ctx);

    const requestedFields: string[] = gqlContext
      .getInfo()
      .fieldNodes[0]?.selectionSet?.selections?.map((field: FieldNode) => {
        // selectionSet is undefined for model fields
        // and it is defined when is a selection from a nested model
        if (field.selectionSet === undefined) {
          return field.name.value;
        }
      })
      // remove the undefined values generated by node with defined selectionSet
      .filter((value) => value !== undefined);

    return requestedFields;
  },
);
