version: '3.8'

services:
  openapi:
    image: redocly/redoc:v2.1.3
    restart: always
    environment:
      SPEC_URL: openapi-docs.json
      REDOC_OPTIONS: "sort-tags-alphabetically path-in-middle-panel required-props-first side-nav-style='path-only'"
    ports:
      - 8082:80
    volumes:
      - ./docs/openapi/openapi-docs.json:/usr/share/nginx/html/openapi-docs.json:ro

  compodoc:
    image: nginx:1.25.3-alpine3.18
    restart: always
    ports:
      - 8092:80
    volumes:
      - ./docs/compodoc:/usr/share/nginx/html:ro
