name: Deploy to Docker Hub

on:
  pull_request:
    branches: 
      - main
    types: [closed]

# see: https://github.com/docker/build-push-action
jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker base image with shared node_modules
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: poc-nestjs-base:latest
      
      - name: Build and push image for Auth Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/auth-service/Dockerfile
          push: true
          tags: shimisnow/pocnestjs-auth-service:latest

      - name: Build and push image for Financial Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/financial-service/Dockerfile
          push: true
          tags: shimisnow/pocnestjs-financial-service:latest
        