name: Lint • Test

on:
  pull_request:
    branches:
      - 'milestone-**'
      - develop
      - staging

env:
  NODE_VERSION: 22.9.0

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore npm cache
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true

      #- name: Install dependencies
      #  run: npm ci --no-audit

      - name: Lint all apps
        run: npx nx run-many --targets=lint --projects='shared,auth-service,auth-service-e2e,financial-service,financial-service-e2e'

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore npm cache
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true

      #- name: Install dependencies
      #  run: npm ci --no-audit

      - name: Unit and Integration tests
        run: npx nx run-many --targets=test --projects='shared,auth-service,financial-service' --coverage --coverageReporters=cobertura

      - name: SHARED - Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: github.event_name == 'pull_request'
        with:
          filename: coverage/shared/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'

      - name: SHARED - Rename report file
        if: github.event_name == 'pull_request'
        run: mv code-coverage-results.md shared-code-coverage-results.md

      - name: SHARED - Cache coverage report
        uses: actions/cache/save@v4
        if: github.event_name == 'pull_request'
        with:
          path: shared-code-coverage-results.md
          key: ${{ runner.os }}-shared-coverage-report-${{ github.run_id }}-${{ github.run_attempt }}

      - name: AUTH-SERVICE - Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: github.event_name == 'pull_request'
        with:
          filename: coverage/apps/auth-service/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'

      - name: AUTH-SERVICE - Rename report file
        if: github.event_name == 'pull_request'
        run: mv code-coverage-results.md auth-service-coverage-results.md

      - name: AUTH-SERVICE - Cache coverage report
        uses: actions/cache/save@v4
        if: github.event_name == 'pull_request'
        with:
          path: auth-service-coverage-results.md
          key: ${{ runner.os }}-auth-service-coverage-report-${{ github.run_id }}-${{ github.run_attempt }}

      - name: FINANCIAL-SERVICE - Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: github.event_name == 'pull_request'
        with:
          filename: coverage/apps/financial-service/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 90'

      - name: FINANCIAL-SERVICE - Rename report file
        if: github.event_name == 'pull_request'
        run: mv code-coverage-results.md financial-service-coverage-results.md

      - name: FINANCIAL-SERVICE - Cache coverage report
        uses: actions/cache/save@v4
        if: github.event_name == 'pull_request'
        with:
          path: financial-service-coverage-results.md
          key: ${{ runner.os }}-financial-service-coverage-report-${{ github.run_id }}-${{ github.run_attempt }}

  coverage-report:
    if: github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Restore shared code report
        uses: actions/cache/restore@v4
        with:
          path: shared-code-coverage-results.md
          key: ${{ runner.os }}-shared-coverage-report-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Restore auth-service report
        uses: actions/cache/restore@v4
        with:
          path: auth-service-coverage-results.md
          key: ${{ runner.os }}-auth-service-coverage-report-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Restore financial-service report
        uses: actions/cache/restore@v4
        with:
          path: financial-service-coverage-results.md
          key: ${{ runner.os }}-financial-service-coverage-report-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Set title for shared code
        run: |
          cat <<EOF >> code-coverage-output.md
          ## 📦 Shared

          EOF

      - name: Merge shared report file
        run: cat shared-code-coverage-results.md >> code-coverage-output.md

      - name: Set title for auth-service
        run: |
          cat <<EOF >> code-coverage-output.md

          ## 📦 Auth Service

          EOF

      - name: Merge auth-service report file
        run: cat auth-service-coverage-results.md >> code-coverage-output.md

      - name: Set title for financial-service
        run: |
          cat <<EOF >> code-coverage-output.md

          ## 📦 Financial Service

          EOF

      - name: Merge financial-service report file
        run: cat financial-service-coverage-results.md >> code-coverage-output.md

      - name: Set final PR message
        run: |
          cat <<EOF >> code-coverage-output.md

          ⛔️ This comment can be replaced by Github Actions. Do not quote or react to it.
          EOF

      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: code-coverage
          recreate: true
          path: code-coverage-output.md
