name: Development - Unit Testing

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.1.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Unit test for AUTH SERVICE
        run: npx nx test auth-service
